{{- if and (not .Values.bootstrap.existingSecret) .Values.bootstrap.admin .Values.bootstrap.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.bootstrap.secretName }}
  labels:
    app.kubernetes.io/name: {{ include "gfs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  GFS_BOOTSTRAP_ADMIN: {{ .Values.bootstrap.admin | quote }}
  GFS_BOOTSTRAP_PASSWORD: {{ .Values.bootstrap.password | quote }}
{{- end }}
{{- if and (eq .Values.topology "vps-s3") (not .Values.s3.existingSecret) .Values.s3.accessKeyId .Values.s3.secretAccessKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.s3.secretName }}
  labels:
    app.kubernetes.io/name: {{ include "gfs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey | quote }}
{{- end }}
